// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPQuKFFQjefPLXET8oXSWeQA3ZM3oL_5A',
    appId: '1:159533889035:web:a37b12f5dfc47e6389790e',
    messagingSenderId: '159533889035',
    projectId: 'expense-split-aashil',
    authDomain: 'expense-split-aashil.firebaseapp.com',
    storageBucket: 'expense-split-aashil.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1cPUjFfsSWwaDoN-bhCkkdDRKg1TpUY8',
    appId: '1:159533889035:android:92613a985923e58889790e',
    messagingSenderId: '159533889035',
    projectId: 'expense-split-aashil',
    storageBucket: 'expense-split-aashil.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfz_EMJHRJzLjnXupFWkJcuh3B1pkoRI4',
    appId: '1:159533889035:ios:f9b24f3285f226a189790e',
    messagingSenderId: '159533889035',
    projectId: 'expense-split-aashil',
    storageBucket: 'expense-split-aashil.firebasestorage.app',
    iosBundleId: 'com.example.expenseSplit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfz_EMJHRJzLjnXupFWkJcuh3B1pkoRI4',
    appId: '1:159533889035:ios:f9b24f3285f226a189790e',
    messagingSenderId: '159533889035',
    projectId: 'expense-split-aashil',
    storageBucket: 'expense-split-aashil.firebasestorage.app',
    iosBundleId: 'com.example.expenseSplit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPQuKFFQjefPLXET8oXSWeQA3ZM3oL_5A',
    appId: '1:159533889035:web:2fa423d1bea7d7e689790e',
    messagingSenderId: '159533889035',
    projectId: 'expense-split-aashil',
    authDomain: 'expense-split-aashil.firebaseapp.com',
    storageBucket: 'expense-split-aashil.firebasestorage.app',
  );
}
